### PR TITLE
fix bless({}, 'ARRAY') issue

### PR DESCRIPTION
**Pull request by tobyink**
Slows things down a little, but fixes the issue.

I'll leave it to you to decide whether it's worth the slow down.

### CODE REVIEW

**Comment by tobyink** [comment]
Also I meant `Scalar::Util::blessed( $_[0] )` of course.

D'oh!

**Comment by tobyink** [comment]
Oh yeah, and Scalar::Util is in core since 5.7.x, so it doesn't introduce any additional dependencies. (List::Flat already specifies a minimum Perl version of 5.8.1.)

**Comment by aaronpriven** [comment]
Is "bless {}, 'ARRAY'" a real thing that might happen, outside of an even-more-obfuscated-than-usual Perl contest? Because it seems pretty pathological to me. I mentioned it in the documentation mainly for completeness.

**Comment by tobyink** [comment]
Pretty sure I've done it in the past, but I tend to do a lot of crazy things.

**Comment by aaronpriven** [comment]
I'm sure any programmer running into that issue is fully capable of writing their own "flat" routine. Probably using Inline::Intercal.

**Pull request closed without merging**
